# Netlify configuration for Vue.js SPA
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

# This redirect is ESSENTIAL for Single Page Applications like Vue.js
# It ensures all routes return the index.html file so Vue Router can handle them
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proper MIME type configuration for JavaScript files
[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

# Configuration for ES Modules
[[headers]]
  for = "/*.mjs"
    [headers.values]
    Content-Type = "application/javascript"

# Configuration for JSON files (including manifest)
[[headers]]
  for = "/*.json"
    [headers.values]
    Content-Type = "application/json"

# Specific configuration for manifest file
[[headers]]
  for = "/manifest.json"
    [headers.values]
    Content-Type = "application/manifest+json"

# Cache control for static assets to improve performance
[[headers]]
  for = "/static/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file