[build]
  command = "npm run build"
  publish = "dist"

# This redirect is ESSENTIAL for Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proper MIME types for Vite's output files
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/*.json"
    [headers.values]
    Content-Type = "application/json; charset=utf-8"

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file